### ISSUE TITLE
No module named 'resource' on Windows

### ISSUE THREAD

**Issue by mariusves** [FRESNA/PyPSA#9]
After upgrading to 0.7.0 importing PyPSA raises the error:

```
Traceback (most recent call last):

  File "<ipython-input-1-204dc4f75877>", line 1, in <module>
    import pypsa

  File "C:\Users\Marius\Anaconda3\lib\site-packages\pypsa\__init__.py", line 27, in <module>
    from . import components

  File "C:\Users\Marius\Anaconda3\lib\site-packages\pypsa\components.py", line 60, in <module>
    from .contingency import (calculate_BODF, network_lpf_contingency,

  File "C:\Users\Marius\Anaconda3\lib\site-packages\pypsa\contingency.py", line 42, in <module>
    from .opt import l_constraint

  File "C:\Users\Marius\Anaconda3\lib\site-packages\pypsa\opt.py", line 37, in <module>
    import resource

ImportError: No module named 'resource'
```
I'm using Windows 10 and Python 3.5.1 currently, so maybe "resource" is linux only?

**Comment by coroa** [comment]
Hi Marius,

Thanks for raising. I should have checked that it is available for
everyone.

A bugfix release should follow soon.

Jonas
